name: Build & Push Multi-Arch Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image Tags
        id: vars
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "TAG_NAME=$TAG_NAME"
          echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/docker-openvpn:$TAG_NAME,${{ secrets.DOCKERHUB_USERNAME }}/docker-openvpn:latest" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.vars.outputs.tags }}
